version: "3.9"

services:
  app:
    container_name: app_node
    build: .
    env_file:
      - .env
    ports:
      - $PORT:$PORT
    depends_on:
      postgres:
        condition: service_healthy
    command: bash -c "yarn typeorm migration:run -d src/data-source && yarn dev"
    volumes:
      - .:/app

  postgres:
    container_name: pg_db
    image: postgres:14.6
    env_file:
      - .env
    ports:
      - $PGPORT:$PGPORT
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s